# Домашнее задание "Линейная алгебра. Матрицы".

## Уровень 0:


### Задание 1

 - Создайте матрицу 3 на 3, заполненную числами от 1 до 9
 - Прибавьте к ней матрицу с единицами на диагонале
 - Умножьте полученную матрицу на вектор (1, 2, 3)
 - Вычислить транспонированную матрицу $A^T$ от полученной в результате прибавления матрицы
 - Посчитайте обратную матрицу к полученной в результате прибавления матрице


In [ ]:
import numpy as np

In [ ]:
#Вариант 1: Создаём матрицу 3 на 3 (в данном случае это "телефонная" матрица)
A1=np.array([[1,2,3],[4,5,6],[7,8,9]])
A1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
##Вариант 2: Создаём матрицу 3 на 3 (в данном случае это "телефонная" матрица)
matrix = np.arange(1,10).reshape(3,3)
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
#Создаём единичную матрицу 3 на 3
A2=np.eye(3,3)
A2

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
#Складывем первоначальную матрицу с единичной
A3=A1+A2
A3

array([[ 2.,  2.,  3.],
       [ 4.,  6.,  6.],
       [ 7.,  8., 10.]])

In [ ]:
#Создаём вектор согласно условию
a=np.array([1,2,3])
a

array([1, 2, 3])

In [ ]:
#Умножаем матрицу А3 на вектор а (Используем матричное умножение, а не поэлементное (когда умножение с использоваием знака *))
A4=A3@a
A4

array([15., 34., 53.])

In [ ]:
#Транспонируем матрицу А3
A5t=np.transpose(A3)
A5t

array([[ 2.,  4.,  7.],
       [ 2.,  6.,  8.],
       [ 3.,  6., 10.]])

In [ ]:
#Находим матрицу, обратную матрице А3
A6=np.linalg.inv(A3)
A6

array([[-6.00000000e+00, -2.00000000e+00,  3.00000000e+00],
       [-1.00000000e+00,  5.00000000e-01, -2.33146835e-16],
       [ 5.00000000e+00,  1.00000000e+00, -2.00000000e+00]])

## Уровень 1:

### Задание 2

Найдите собственные значения и собственные вектора матрицы:
```
m = np.array([[2, 2],
              [1, 3]])
print(m)
```



In [ ]:
m=np.array([[2,2], [1,3]])
m

array([[2, 2],
       [1, 3]])

In [ ]:
#Находим собственные значения матрицы m
np.linalg.eigvals(m)

array([1., 4.])

In [ ]:
#Находим собственные вектора матрицы m
np.linalg.eig(m)

EigResult(eigenvalues=array([1., 4.]), eigenvectors=array([[-0.89442719, -0.70710678],
       [ 0.4472136 , -0.70710678]]))

### Задание 3


Придумайте матрицу, у которой определитель = 1, и все элементы не равны 0.

P.S. Матрица должна быть ненулевой и размерностью не менее 2!

In [ ]:
#Пример матрицы 2 на 2 с определителем 1
M = np.array([[2,3],[3,5]])
M


array([[2, 3],
       [3, 5]])

In [ ]:
#Проверяем, действительно ли определитель матрицы М равен 1
np.linalg.det(M)

0.9999999999999991

In [17]:
#Создаём матрицу 3 на 3 через перебор
det = 0
while det !=1:
    k = np.random.randint(-10,10,(3,3))
    det = np.linalg.det(k)
print('Искомая матрица: \n', k)

Искомая матрица: 
 [[-1  4  4]
 [ 1 -1  3]
 [-2  6  3]]


In [18]:
np.linalg.det(k)

1.0